apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: ethnicbadger/duo-flask:latest
    ports:
    - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer